### ISSUE TITLE
Running the PhysiCell sample projects

### ISSUE THREAD

**Issue by sessler** [MathCancer/PhysiCell#131]
I have set up physicell (by the way the installation manual is very well written and easy to follow) and trid to run the first sample project and got an error message: 
BioFVM_vector.o: file not recognized: file format not recognized
collect2.exe: error: ld returned 1 exit status
make: *** [all] Error 1
<img width="1388" alt="a" src="https://user-images.githubusercontent.com/5181054/206437163-dfb9e0a9-e8a1-476b-bb69-b2f642f5be11.png">

**Comment by rheiland** [comment]
How exactly did you install g++ (mingw) on Windows? Did you follow the Windows pdf found here: https://github.com/physicell-training/ws2022/tree/main/setup which instructs you to download/run this Python script: https://github.com/physicell-training/ws2022/blob/main/setup/get_physicell.py ? If not, could you please try that. If you still have problems, please report results from this command in a terminal shell `g++ --version` and provide info about your Windows system - is it Windows 10, 11? Processor?

**Comment by MathCancer** [comment]
Thank you so much. Yes, we are in desperate need of an update on blogs / tutorials / user manual. 

At the least, we need to provide bread crumbs. This is definitely on my radar. 

Thank you!
