### ISSUE TITLE
bogus BioFVM_vector.o in 1.10.4 release

### ISSUE THREAD

**Issue by rheiland** [MathCancer/PhysiCell#132]
There's a BioFVM_vector.o file included in the 1.10.4 release which apparently causes problems when compiling on Windows with MinGW g++ (HT to Michael Getz). We'll want to make sure there are no extraneous .o files in future releases.

**Comment by MathCancer** [comment]
Thanks, good point. I'll make sure to do a make clean as part of release protocol.
