### ISSUE TITLE
standalone <molecular/>  tag in PhysiCell_settings.xml

### ISSUE THREAD

**Issue by elmbeech** [MathCancer/PhysiCell#137]
i run 
```
make reset
make temple
```
after that, in the granted `PhysiCell_settings.xml` is a standalone `<molecular/>` tag, line 315.
I am not a pro in xml, but this looks strange to me.

**Comment by MathCancer** [comment]
Thanks. 
That's a bit of a "stub" for a path we didn't pursue, since "intracellular" became preferred. 

but `<molecular/>` is valid XML.
