### ISSUE TITLE
duplicate/confusing assignment for maximum_attachment_rate

### ISSUE THREAD

**Issue by rheiland** [MathCancer/PhysiCell#146]
There's currently a duplicate assignment for `maximum_attachment_rate` in the Mechanics constructor. Wondering if one should be for detachment_rate? Currently at this location in the dev branch:
https://github.com/MathCancer/PhysiCell/blob/development/core/PhysiCell_phenotype.cpp#L702

**Comment by MathCancer** [comment]
removed the dupe. 

Attachment and detachment rates are already initialized in the constructor. 

Thanks!
