### ISSUE TITLE
TravisCI for Continuous Integration (CI)

### ISSUE THREAD

**Issue by rheiland** [MathCancer/PhysiCell#15]
I'd like for us to begin using CI for PhysiCell. This is an important step in maintaining quality software. There are many CI services to choose from (that play well with github). I propose we just start with [TravisCI](https://travis-ci.com/). 
1. an Admin (Paul) needs to sign up at TravisCI (using your github sign-in) then tell it to connect to this repo. 
2. we need to add a .travis.yml file to our repo (root) that provides instructions on what we want done for CI.

I've made a [google doc](https://docs.google.com/document/d/1yn7-KtFgl2IS-g3sWKFAPdJqmizKXoFfD4zVjyHzMOg/edit?usp=sharing) that will hopefully help walk through these initial steps. We'll iterate & improve as we go.

**Comment by MathCancer** [comment]
We have added this to the dev branch. While more development is definitely an ongoing topic, I am going to mark this closed for now.
