### ISSUE TITLE
Improvement: code generates output folder 

### ISSUE THREAD

**Issue by elmbeech** [MathCancer/PhysiCell#183]
physicell will run into an error if there not already an output folder exist (with whatever the exact name specified under <save> in the settings.xml).
it would be nice if the physicell in the beginning automatically checks if such a folder exists and, if not, generate it.

**Comment by MathCancer** [comment]
That's a good idea. Let's revisit this for 1.13.2.

**Comment by elmbeech** [comment]
this is how it how i do it currently by bash.

```bash
!if [ ! -d output ]; then mkdir -p output; fi;
```

**Comment by elmbeech** [comment]
resolved by [pull request #235](https://github.com/MathCancer/PhysiCell/pull/235)
solved in the `template` project code.

**Comment by elmbeech** [comment]
Resolved with the coming PhysiCell release 1.14 (or 1.13.2).
