### ISSUE TITLE
Normalization in void normalize( std::vector<double>* v ) function in BioFVM_vector.cpp

### ISSUE THREAD

**Issue by johnmetzcar** [MathCancer/PhysiCell#24]
The function void normalize (std::vector<double>* v) on lines 206 - 217 of BioFVM_vector.cpp, does not catch when a very very small (a vector with components  within a small epsilon of zero but magnitude greater than zero) vector is sent to the function.  As discussed offline, we propose adding a tolerance to the normalization routine such that the normalize function returns the zero vector when the magnitude of vector v is less than some small epsilon. 

Here is some propose example code to put around line 213:

if (norm < 1e-16)
{
 for( unsigned int i=0; i < v->size(); i++ )
 { (*v)[i] =  0 ; }
}

**Comment by MathCancer** [comment]
This fix is in 1.6.1
