### ISSUE TITLE
PhysiCell::Cell_Definition possibly memory leaking

### ISSUE THREAD

**Issue by elmbeech** [MathCancer/PhysiCell#263]
I get a `Segmentation fault (core dumped)`, if I try to generate a second instance of a Cell_Definition.
Reading up on this, this potentially points to a memory leaking.

Minimal example:

1. rest to a fresh PhysiCell installation.
```
make clean reset
make template
```

2. add the following line to `custom_modules/custome.cpp`.
```
PhysiCell::Cell_Definition cell_defaults_two;
```

3. compile and run the template project.
```
make 
./project
```

I will have to study the code in deep and use a debugger to resolve this issue.

**Comment by rheiland** [comment]
Your reason for wanting to create a second instance of a Cell_Definition escapes me, but just as an academic exercise, I took a closer look and created a repo to demonstrate. Do NOT do a `make reset`, just `make` and run `project`. Take a look at the modified/simplified `main.cpp` and the `custom.cpp`. Bottom line: the `cell_defaults` instance (in `core/PhysiCell_cell.cpp`) is quite special and has a long history which includes how cell definitions have evolved. Nevertheless, hopefully this repo is instructive: https://github.com/rheiland/second_cell_defaults_instance

Having said that, yes, I encourage you (and anyone else) to use a debugger to track down where segfaults occur. In this case, it's not a memory leak.

**Comment by elmbeech** [comment]
this is very helpfull.
