### ISSUE TITLE
Physicell studio run simulation error

### ISSUE THREAD

**Issue by sessler** [MathCancer/PhysiCell#313]
Newly installed phisicell studio app gives Exec file ...\PhysiCell_V.1.14.0\PhysiCell\project.exe does not exist. I tried to load a sample project, but got the same error message

**Comment by rheiland** [comment]
Try running `python download_binary.py` - that script should be in the root directory of your studio folder. It should download `project.exe`

**Comment by sessler** [comment]
thank you it solved the problem
Judit

Randy Heiland ***@***.***> ezt írta (időpont: 2024. okt. 18.,
P, 3:44):
