### ISSUE TITLE
"make data-cleanup" error 

### ISSUE THREAD

**Issue by fairliereese** [MathCancer/PhysiCell#33]
I'm getting an error when running "make data-cleanup".  It comes from the line
`rm -f ./output/*`
It has to do with there being too many objects for `rm` to remove. For instance, biorobots-sample produces ~7.2k files in the output directory.  (https://support.qualityunit.com/257075-rm-and-the-Argument-list-too-long-error-message)

The error I get is: 
/bin/sh: /bin/rm: Argument list too long
make: *** [data-cleanup] Error 126

My workaround was replacing the above makefile command with 
`rm -r ./output/`
`mkdir ./output/`

I'm running bash on MacOS Catalina 10.15.2.

**Comment by rheiland** [comment]
Thank you for reporting this! I can confirm that I get this same "Argument list too long" on macOS 10.14 (Mojave). I have no doubt your workaround is correct, for your OS. I was also able to use:
```
	rm -rf output
	mkdir output
```
We will need to test on the other two supported OSes.

**Comment by MathCancer** [comment]
This is tested in CMD and powershell in Windows: 

data-cleanup:
	rm -f *.mat
	rm -f *.xml
	rm -f *.svg
	rm -rf ./output
	mkdir ./output
	touch ./output/empty.txt

Does it work in OSX and Linux?

**Comment by MathCancer** [comment]
If so, I'll roll it out to all the sampel makefiles

**Comment by rheiland** [comment]
No, the above does not work on OSX:
...
rm -rf ./output
touch ./output/empty.txt
touch: ./output/empty.txt: No such file or directory
make: *** [data-cleanup] Error 1

However, if we instead use:
rm -f ./output/*

it works on OSX. What about Windows?

Also, I personally find this target a bit dangerous as I tend to keep additional config files (.xml) in my root dir and use them for testing. This data-cleanup target would delete them. But that's just me and I don't ever use this target.

**Comment by MathCancer** [comment]
I thought  

rm -f ./output/* 

was what we have now, but it generates the long argument list that lead to this bug report. So we wanted a cross-platform solution. I note that yours above does not have "mkdir ./output". 

'''
data-cleanup:
rm -f *.mat
rm -f *.xml
rm -f *.svg
rm -rf ./output
**mkdir ./output**
touch ./output/empty.txt
'''

**Comment by MathCancer** [comment]
(The "touch" is so that it can make a 0 kb file. This in turn makes sure the directory is non-empty, so it doesn't disappear in github.)

**Comment by rheiland** [comment]
Argh, sorry. Yes, the original poster's situation was due to LOTS of output files in /output. So, yes, your last data-cleanup steps, including the `rm -rf ./output` and `mkdir ./output` and `touch ...` should indeed be a proper fix. It works on OSX, and even though I didn't test with perhaps as many output files as the OP, I feel confident it will work in that case too.

**Comment by MathCancer** [comment]
OK, great! 
I'll start working that through the makefiles

**Comment by MathCancer** [comment]
OK, the fix is now in the dev branch slated for release in 1.7.0 in early or mid March. Thank you!
