### ISSUE TITLE
invalid index if substrate not present in .xml causes SIGABRT

### ISSUE THREAD

**Issue by rheiland** [MathCancer/PhysiCell#47]
initialize_cell_definition_from_pugixml----------- substrate_name (for chemotaxis) = 
initialize_cell_definition_from_pugixml----------- pMot->chemotaxis_index= -1

				std::string actual_name = microenvironment.density_names[ pMot->chemotaxis_index ];

**Comment by MathCancer** [comment]
Can you please add to the SF ticket tracker?
