### ISSUE TITLE
Recommended UI Changes

### ISSUE THREAD

**Issue by PrudhviVajja** [MathCancer/PhysiCell#53]
For better User experience:
- Move the About tab to the right if you are using the same layout as to bottom as in the pic below.
- [Plotly](https://plotly.com) module has a rich graphical representation than Matplotlib.

<img width="633" alt="Screen Shot 2020-06-25 at 2 40 38 PM" src="https://user-images.githubusercontent.com/34853447/85779716-e3983c80-b6f1-11ea-89a7-1c22201a7724.png">

**Comment by MathCancer** [comment]
Thank you! These look like nice ideas. @rheiland how feasible is this? 

Also, this relates to xml2jupyter (the utility to create GUIs) and not to PhysiCell (the core modeling framework that is the "engine"), so we may want to move this ticket. 

Thank you!

**Comment by rheiland** [comment]
Yes, thanks Prudhvi. I do appreciate you taking a more active role - beyond
"just" testing. I have looked into plotly in the past. However, we have a
significant investment in using matplotlib (and ipywidgets) for the GUI
(xml2jupyter) at this point; switching to something else would require a
significant investment and not something that is high on my priority list.
However, if you are familiar with plotly and would like to make a pull
request (or just offer an informal demo sometime), it would be very
welcome. And keep in mind, a significant amount of our investment goes into
the xml2jupyter idea: taking the XML config file and auto-generating parts
of the GUI. We would need something analogous for plotly.

And, yes, for future ref, this issue probably belongs in
https://github.com/PhysiCell-Tools/PhysiCell-Jupyter-GUI

-Randy

**Comment by MathCancer** [comment]
Awesome!

If you're interested in doing a short-term fork to experiment with plotly,
I'm all ears! :-)


*Sorry for brevity of response – deeply immersed in covid19 work right now.*
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
*Paul Macklin, Ph.D.*
Associate Professor
Director of Undergraduate Studies
*Intelligent Systems Engineering*

*Indiana University*
Founder and Lead of PhysiCell <http://PhysiCell.org>and MultiCellDS
<http://MultiCellDS.org>
*mobile*: 626-372-1203
email: macklinp@iu.edu
email: Paul.Macklin@MathCancer.org
web: MathCancer.org
Twitter: @MathCancer
<https://twitter.com/MathCancer>

**Comment by MathCancer** [comment]
no response in ~2 years. I think we can close this.
